### PR TITLE
build: major paragon version upgrade

### PR DESCRIPTION
**Pull request by Mashal-m**
Major version upgrade of `@edx/paragon`.

This depends on the PR [84](https://github.com/edx/frontend-app-communications/pull/84) which is why the build is failing. Both PRs should be merged together.

### CODE REVIEW

**Comment by Mashal-m** [comment]
review requested [here](https://twou.slack.com/archives/C04AGGN7420/p1671091400984239)

**Review by MaxFrank13 — CHANGES_REQUESTED** [review]
I've approved [PR #84](https://github.com/edx/frontend-app-communications/pull/84#pullrequestreview-1219937078) to remove es5 and add the shared browserlist configuration.

In the [Paragon changelogs for v20](https://github.com/openedx/paragon/releases/tag/v20.0.0) is says that we will need some additional configuration to avoid breaking changes. Specifically it says to add Paragon's messages during initialization. Could you please add those to this PR? Or perhaps there is a reason they are not needed here?

Thanks for doing this work

**Comment by Mashal-m** [comment]
> I've approved [PR #84](https://github.com/edx/frontend-app-communications/pull/84#pullrequestreview-1219937078) to remove es5 and add the shared browserlist configuration.
> 
> In the [Paragon changelogs for v20](https://github.com/openedx/paragon/releases/tag/v20.0.0) is says that we will need some additional configuration to avoid breaking changes. Specifically it says to add Paragon's messages during initialization. Could you please add those to this PR? Or perhaps there is a reason they are not needed here?
> 
> Thanks for doing this work

You are right, I have added Paragon's messages. thanks

**Review by MaxFrank13 — APPROVED** [review]

**Comment by MaxFrank13** [comment]
Thanks for the changes. I made the mistake of re-running the failed job without the changes from PR #84. That PR has been merged so a rebase with master should do the trick I believe?

**Comment by Mashal-m** [comment]
@MaxFrank13 I am closing this because there are a lot of conflicts in the JSON file. I have created new [117](https://github.com/openedx/frontend-app-communications/pull/117).

**Pull request closed without merging**
