### PR TITLE
fix: Added maxLength and default tip for email subject

### PR DESCRIPTION
**Pull request by Inferato**
If the user puts more than 128 symbols in the email subject it causes an error.
изображение

Added length restriction and field tip.
Related PR: https://github.com/openedx/frontend-app-communications/pull/154

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Inferato!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by arbrandes** [comment]
Would it be too much to ask for a screenshot with the error message showing?

**Comment by Inferato** [comment]
> Would it be too much to ask for a screenshot with the error message showing?

Yeah. I'll added it to the description

**Comment by Inferato** [comment]
@arbrandes Screenshot was added. FYI

**Comment by arbrandes** [comment]
Thank you!  But I'd also like to see one with the error pop-up introduced in this PR.  Can you attach one?

**Comment by mphilbrick211** [comment]
> Thank you! But I'd also like to see one with the error pop-up introduced in this PR. Can you attach one?

@Inferato - flagging this for you!

**Comment by mphilbrick211** [comment]
Hi @Inferato! Friendly reminder re: Adolfo's request above. Thanks!

**Comment by mphilbrick211** [comment]
> Hi @Inferato! Friendly reminder re: Adolfo's request above. Thanks!

@Inferato - just following up on this!

**Comment by dyudyunov** [comment]
@arbrandes @mphilbrick211 

Sorry for the delays, Taras is no longer a member of RG.
Currently, I'm gathering all the PRs he worked on. I will check their statuses and update them if necessary.

I will leave the status update comments on each PR's comments.

**Comment by dyudyunov** [comment]
@arbrandes I switched to Taras' branch and checked the behavior.

His fix adds the form help text and limits the subject input to 128 chars
image

Notes:
- the help text `(Maximum 128 characters)` is always displayed (since the page loading)
- according to changes I was not able to send emails with subject length > 128 chars
- I reproduced the issue without Taras' changes on Quince (500 error when there are more than 128 chars)

**Comment by openedx-webhooks** [comment]
@Inferato 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-communications&entry.867055334=https://github.com/openedx/frontend-app-communications/pull/154&entry.1484655318=https://github.com/Inferato&entry.752974735=2023-10-06+11:31&entry.1917517419=2024-02-27+18:14&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
