### PR TITLE
feat: send email students course

### PR DESCRIPTION
**Pull request by johnvente**
### Description

This feature will allow sending emails to the expected email addresses of individuals in the course.

This pr depends on this one: https://github.com/openedx/edx-platform/pull/33463

**DEMO**

mfe-communications2

#### Why are we doing this?

Sometimes, instructors would like to send emails to specific individuals in the course, rather than sending them to the options that are currently available. With this change, it would be easier to do so. The instructor would be able to select any option as well, including **"Myself"**, **"Staff/Administrators"**, **"Learners in the verified certificate track"** except for **"All Learners"**

-----------------------------------------------------------------------------------------------------------------------------------------------------

**How to test it**

If you are using devstack

**1.** Go to workspace and clone this branch
```
cd ~/workspace && git clone -b jv/feat-send-email-students-course git@github.com:eduNEXT/frontend-app-communications.git
```
**2.** Go to the mfe repository, use node version in the repo and install dependencies

```
cd ~/workspace/frontend-app-communications && nvm use && npm install

```
**3.** inside frontend-app-communications run 

```
npm run start
```
**4.** Go to http://localhost:1984/courses/course-v1:edX+DemoX+Demo_Course/bulk_email Or  
http://localhost:1984/courses/{{id_course}}/bulk_email

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @johnvente!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by mphilbrick211** [comment]
Hi @openedx/2u-aperture! Would someone be able to please review/merge for us? Thanks!

**Comment by hurtstotouchfire** [comment]
@mphilbrick211 This repo should have a community maintainer. I defer to the maintainers on whether they have any agreements with the internal owners on the 2U side, but it should be going through the community maintainers first.

**Comment by arbrandes** [comment]
For the record, I think the PR to edx-platform should be reviewed/merged before we get to this one.

**Comment by felipemontoya** [comment]
@arbrandes one idea that I have been going around in my head would be to convert this PR to an extension mechanism like tue UISlot that braded proposed at the summit. We would create an extendable Slot where the checkboxes/filters are and we would do the email type box there.

Would you review/approve such architecture for this Adolfo? I would not like to go back from this and later not find anyone that could help us review the refactor. I'm asking you as the temp maintainer of this repo.

**Comment by arbrandes** [comment]
@felipemontoya, in principle, yes, I'd be happy to review the introduction of an extension mechanism here!  I'm just unsure if this particular use case is a good candidate for a plugin: the backend changes that go with it are pretty tightly nit with the rest of the code.

If, however, the bulk email backend can be made pluggable - maybe via hooks? - then it would make more sense to make the frontend pluggable as well.

**Comment by felipemontoya** [comment]
Yes, that is exactly what we are thinking. We would move the platform PR to a plugin and the front end PR as well. But the extension mechanism needs to first exist in this repo.

**Comment by arbrandes** [comment]
@felipemontoya

> the extension mechanism needs to first exist in this repo

Deal! 🤝

**Comment by mphilbrick211** [comment]
Hi @arbrandes and @johnvente! Just checking in on this one.

**Comment by arbrandes** [comment]
@mphilbrick211, I suspect this one will be refactored based on the outcome on the plugin slot implementation:

https://github.com/openedx/frontend-app-communications/pull/184

**Comment by mphilbrick211** [comment]
> @mphilbrick211, I suspect this one will be refactored based on the outcome on the plugin slot implementation:
> 
> #184

Any updates, @arbrandes?

**Comment by felipemontoya** [comment]
@johnvente can we close this as the actual feature is happening on #184? is there anything from this PR that needs salvaging?

**Comment by johnvente** [comment]
@felipemontoya We do not need this pr anymore with the UI slot implemented I will close this 
cc: @mphilbrick211

**Comment by openedx-webhooks** [comment]
@johnvente Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-communications&entry.867055334=https://github.com/openedx/frontend-app-communications/pull/157&entry.1484655318=https://github.com/johnvente&entry.752974735=2023-10-10+15:09&entry.1917517419=2024-03-20+21:09&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
