### PR TITLE
feat: upgrade react router to v6

### PR DESCRIPTION
**Pull request by Syed-Ali-Abbas-Zaidi**
## Ticket
[React Router Upgrade to v6](https://github.com/openedx/platform-roadmap/issues/276).

## Description
This PR upgrades React Router from `v5` to `v6`.

### CODE REVIEW

**Comment by justinhynes** [comment]
Hi @Syed-Ali-Abbas-Zaidi -- this PR has been a draft for a few months now. Is there still work left to do? Can we close this? Thanks for any information on the status of the PR.

If the conflicts are fixed up we can work to prioritize a review of the PR.

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
> Hi @Syed-Ali-Abbas-Zaidi -- this PR has been a draft for a few months now. Is there still work left to do? Can we close this? Thanks for any information on the status of the PR.
> 
> If the conflicts are fixed up we can work to prioritize a review of the PR.

Hi @justinhynes, This PR will be ready for review once the router upgrade [PR of frontend-platform](https://github.com/openedx/frontend-platform/pull/422) gets merged.

**Comment by johnvente** [comment]
Hi! [curious] @Syed-Ali-Abbas-Zaidi, how can I test this in parallel with the [[dependency PR]](https://github.com/openedx/frontend-platform/pull/422)

**Review by awais-ansari — APPROVED** [review]

**Review by sundasnoreen12 — APPROVED** [review]
PR LGTM

**Pull request merged**
